### ISSUE TITLE
Content type handler overrides any custom handler

### ISSUE THREAD

**Issue by kerneldemon** [dopesong/Slim-Whoops#2]
If I add a bunch of my custom handlers like so:

```php
$whoopsHandler = new WhoopsError();
$whoopsHandler->pushHandler(new LoggerAwareHandler($logger));
$whoopsHandler->pushHandler(new ApiExceptionHandler());
```

They will be ignored.

This happens because 

1) Content type handler is [the last handler that is pushed](https://github.com/dopesong/Slim-Whoops/blob/2.x/src/Whoops.php#L78) to the internal whoops object
2) Handler collection is iterated over [in reverse](https://github.com/filp/whoops/blob/master/src/Whoops/Run.php#L262)

This means that the handler that was pushed last will always be the first.

One way to solve this would be to add all handlers in reverse.

**Comment by kerneldemon** [comment]
The second option would be to prepend only the default handler (the one that is determined using content-type). I guess other options would require updating the underlying library.

I pushed two branches with those two options.
Any opinions on this?

**Comment by dopesong** [comment]
I think second option is little bit better, because if we going to add more handlers first option will suck anyways.

**Comment by dopesong** [comment]
Nice catch! Thanks for PR!
